#!/usr/bin/env bash
# vmui — first-time setup for the Ubuntu KVM guest (cloud-image flavour).
#
# Run with:  wsl -d Ubuntu-24.04 -- bash /mnt/e/gh/vmui/scripts/setup-ubuntu-vm.sh
#
# What this does:
#   1. Installs QEMU + OVMF + cloud-init utils (genisoimage, mkpasswd).
#   2. Creates ~/vmui-vms/ubuntu and copies OVMF firmware into it.
#   3. Downloads the Ubuntu LTS *cloud image* (qcow2) and turns it into
#      Ubuntu.qcow2 resized to ${DISK_GB}.
#   4. Builds seed.iso (NoCloud cloud-init datasource) which bakes the
#      user/password and installs ubuntu-desktop-minimal + openssh-server
#      on first boot.
#
# Why cloud image (not Desktop ISO):
#   - The Ubuntu Desktop ISO uses the new Flutter installer which has
#     fragile autoinstall support — partial schema mismatches silently
#     skip user creation, leaving GDM with no usable credentials.
#   - Cloud images run cloud-init by default, so user creation, SSH and
#     package install are deterministic. Boot → wait ~5–8 min → SSH works.
#
# Credentials precedence (highest first):
#   1. Env vars UBUNTU_USERNAME / UBUNTU_PASSWORD (passed by caller).
#   2. ~/vmui-vms/ubuntu/vm-creds.env (written by the vmui server action
#      when an account is created from the web UI; sourced here).
#
# There is intentionally no hardcoded fallback — every VM gets its own
# unique credentials, generated by the UI when not user-supplied.
set -euo pipefail

VMDIR="${VMDIR:-$HOME/vmui-vms/ubuntu}"
mkdir -p "$VMDIR"

# Source UI-provided credentials. The server action writes this file with
# UBUNTU_USERNAME and UBUNTU_PASSWORD when a Local-KVM Ubuntu account is
# created; without it we have no creds and bail out.
if [ -f "$VMDIR/vm-creds.env" ]; then
  # shellcheck disable=SC1091
  set -a; . "$VMDIR/vm-creds.env"; set +a
fi

DISK_GB="${DISK_GB:-50}"
USERNAME="${UBUNTU_USERNAME:-}"
PASSWORD="${UBUNTU_PASSWORD:-}"
HOSTNAME_U="${UBUNTU_HOSTNAME:-vmui-ubuntu}"
RELEASE="${UBUNTU_RELEASE:-26.04}"
INSTALL_DESKTOP="${INSTALL_DESKTOP:-1}"  # set to 0 to skip ubuntu-desktop-minimal

if [ -z "$USERNAME" ] || [ -z "$PASSWORD" ]; then
  cat >&2 <<MSG
ERROR: no guest credentials configured.

Expected one of:
  - $VMDIR/vm-creds.env containing UBUNTU_USERNAME and UBUNTU_PASSWORD
    (vmui writes this automatically when you create the account from
     the web UI).
  - UBUNTU_USERNAME=... UBUNTU_PASSWORD=... env vars on the command line.

Connect a Local-KVM Ubuntu account from the web UI to generate creds,
then re-run this script.
MSG
  exit 2
fi

# Ubuntu cloud image (resized in place). 26.04 LTS "Resolute Raccoon"
# (released 2026-04) is the latest LTS as of mid-2026.
# Override with UBUNTU_CLOUDIMG_URL for a different release/arch.
CLOUDIMG_URL_DEFAULT="https://cloud-images.ubuntu.com/releases/${RELEASE}/release/ubuntu-${RELEASE}-server-cloudimg-amd64.img"
CLOUDIMG_URL="${UBUNTU_CLOUDIMG_URL:-$CLOUDIMG_URL_DEFAULT}"

echo "=== [1/5] apt install qemu, ovmf, cloud-init tooling ==="
sudo apt-get update -qq
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq \
  qemu-system-x86 qemu-utils ovmf \
  genisoimage whois curl ca-certificates 2>&1 | tail -5

cd "$VMDIR"

echo
echo "=== [2/5] Copy OVMF firmware ==="
SRC_CODE=""
for cand in /usr/share/OVMF/OVMF_CODE_4M.fd /usr/share/OVMF/OVMF_CODE.fd; do
  if [ -f "$cand" ]; then SRC_CODE="$cand"; break; fi
done
SRC_VARS=""
for cand in /usr/share/OVMF/OVMF_VARS_4M.fd /usr/share/OVMF/OVMF_VARS.fd; do
  if [ -f "$cand" ]; then SRC_VARS="$cand"; break; fi
done
if [ -z "$SRC_CODE" ] || [ -z "$SRC_VARS" ]; then
  echo "ERROR: OVMF firmware files not found under /usr/share/OVMF." >&2
  exit 1
fi
cp -f "$SRC_CODE" OVMF_CODE.fd
[ -f OVMF_VARS.fd ] || cp -f "$SRC_VARS" OVMF_VARS.fd
echo "  CODE: $SRC_CODE"
echo "  VARS: $SRC_VARS  → ./OVMF_VARS.fd"

echo
echo "=== [3/5] Download Ubuntu ${RELEASE} cloud image ==="
if [ -f cloudimg.img ]; then
  echo "  exists, skipping ($(du -h cloudimg.img | cut -f1))"
else
  echo "  fetching $CLOUDIMG_URL"
  curl -L --fail --progress-bar -o cloudimg.img.tmp "$CLOUDIMG_URL"
  mv cloudimg.img.tmp cloudimg.img
fi
ls -lh cloudimg.img | awk '{print "  size:", $5}'

echo
echo "=== [4/5] Build Ubuntu.qcow2 (${DISK_GB} GiB) from cloud image ==="
# We rebuild Ubuntu.qcow2 only if it's missing or older than cloudimg.img to
# avoid clobbering an installed system on a re-run of the setup script.
if [ -f Ubuntu.qcow2 ] && [ "Ubuntu.qcow2" -nt "cloudimg.img" ]; then
  echo "  Ubuntu.qcow2 exists and is newer than cloudimg.img — keeping."
else
  echo "  copying cloudimg.img → Ubuntu.qcow2 and resizing to ${DISK_GB}G"
  cp -f cloudimg.img Ubuntu.qcow2.tmp
  qemu-img resize Ubuntu.qcow2.tmp "${DISK_GB}G"
  mv -f Ubuntu.qcow2.tmp Ubuntu.qcow2
fi
qemu-img info Ubuntu.qcow2 | sed 's/^/  /'

echo
echo "=== [5/5] Build seed.iso (NoCloud cloud-init: user=$USERNAME) ==="
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

# Hash the password with SHA-512 crypt — cloud-init refuses plaintext on
# anything later than 21.x. Use mkpasswd (whois pkg); fall back to openssl.
PWHASH="$(mkpasswd -m sha-512 "$PASSWORD" 2>/dev/null || true)"
if [ -z "$PWHASH" ]; then
  PWHASH="$(openssl passwd -6 "$PASSWORD")"
fi

cat > "$WORK/meta-data" <<META
instance-id: vmui-ubuntu-1
local-hostname: $HOSTNAME_U
META

# Plain cloud-config — cloud images run cloud-init out of the box and read
# /user-data from the NoCloud datasource (the CIDATA-labelled CD).
{
  echo '#cloud-config'
  echo "hostname: $HOSTNAME_U"
  echo 'manage_etc_hosts: true'
  echo 'preserve_hostname: false'
  echo 'disable_root: true'
  echo 'ssh_pwauth: true'
  echo 'timezone: Etc/UTC'
  echo 'users:'
  echo "  - name: $USERNAME"
  echo "    gecos: $USERNAME"
  echo '    groups: [adm, sudo, plugdev, lxd]'
  echo '    shell: /bin/bash'
  echo "    sudo: 'ALL=(ALL) NOPASSWD:ALL'"
  echo '    lock_passwd: false'
  echo "    passwd: \"$PWHASH\""
  echo 'chpasswd:'
  echo '  expire: false'
  echo 'package_update: true'
  echo 'package_upgrade: true'
  echo 'package_reboot_if_required: false'
  echo 'packages:'
  echo '  - openssh-server'
  echo '  - net-tools'
  echo '  - curl'
  echo '  - qemu-guest-agent'
  if [ "$INSTALL_DESKTOP" = "1" ]; then
    echo '  - ubuntu-desktop-minimal'
    echo '  - x11vnc'
  fi
  echo 'runcmd:'
  echo '  - [ systemctl, enable, --now, ssh ]'
  echo '  - [ systemctl, enable, --now, qemu-guest-agent ]'
  if [ "$INSTALL_DESKTOP" = "1" ]; then
    # Make GDM the default boot target *and* enable the service. We do NOT
    # try to switch to graphical.target live in this same boot — GDM is
    # often still finishing post-install configuration when runcmd fires,
    # and `systemctl isolate` silently fails / kills cloud-init's session.
    # Instead we let cloud-init request a reboot via `power_state` below;
    # after the reboot the default target *is* graphical, so GDM comes up
    # cleanly on tty1 with no manual switch.
    echo '  - [ systemctl, set-default, graphical.target ]'
    echo '  - [ systemctl, enable, gdm3 ]'
  fi
  # Marker file we poll from the host to detect "first-boot done".
  echo "  - [ sh, -c, 'echo done > /var/lib/vmui-firstboot.done' ]"
  if [ "$INSTALL_DESKTOP" = "1" ]; then
    echo 'power_state:'
    echo '  mode: reboot'
    echo '  delay: 5'
    echo '  message: "vmui first-boot complete — rebooting into GDM"'
    echo '  condition: True'
  fi
} > "$WORK/user-data"

# meta-data + user-data must live on a volume labelled CIDATA for cloud-init
# to detect it as the NoCloud datasource.
genisoimage -quiet -output seed.iso -volid CIDATA -joliet -rock \
  "$WORK/user-data" "$WORK/meta-data"
ls -lh seed.iso | awk '{print "  size:", $5}'

# Clean up legacy artifacts from the previous desktop-ISO autoinstall flow
# so they don't get attached by boot-ubuntu.sh.
rm -f ubuntu.iso ubuntu-auto.iso 2>/dev/null || true

echo
echo "VM directory : $VMDIR"
ls -1 "$VMDIR"
echo
cat <<EOF
=== ✅ UBUNTU_SETUP_DONE ===

User       : $USERNAME
Password   : (hashed, baked into seed.iso)
Hostname   : $HOSTNAME_U
Disk       : Ubuntu.qcow2 (${DISK_GB}G, resized cloud image)
Desktop    : $([ "$INSTALL_DESKTOP" = "1" ] && echo yes || echo no)

Start the VM via the VS Code task "vmui: start ubuntu VM" or the vmui UI.
First boot runs cloud-init (~3–8 min depending on package install). After
that, SSH works at:  ssh -p 10024 $USERNAME@127.0.0.1
EOF
