"use client";

import { useMemo, useState } from "react";
import { Download, Copy, Check, FileCode } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";

interface SshHost {
  id: string;
  host: string;
  provider: string;
  ip: string;
  keyName: string | null;
  platform: string;
}

const DEFAULT_USER: Record<string, string> = {
  aws: "ec2-user",
  azure: "azureuser",
  gcp: "ubuntu",
  scaleway: "m1",
  "local-kvm": "ubuntu",
};

function safeAlias(s: string): string {
  return s.replace(/[^a-zA-Z0-9_.-]/g, "-").toLowerCase();
}

export function SshConfigExport({ instances }: { instances: SshHost[] }) {
  const [copied, setCopied] = useState(false);
  const linuxOnly = useMemo(() => instances.filter((i) => i.platform !== "windows"), [instances]);

  const config = useMemo(() => {
    const lines: string[] = [
      "# Generated by vmui — drop in ~/.ssh/config or include via 'Include ~/.ssh/config.d/vmui'",
      "",
    ];
    for (const i of linuxOnly) {
      const alias = `vmui-${safeAlias(i.host)}`;
      const user = DEFAULT_USER[i.provider] ?? "root";
      lines.push(`Host ${alias}`);
      lines.push(`  HostName ${i.ip}`);
      lines.push(`  User ${user}`);
      if (i.keyName) lines.push(`  # AWS keypair: ${i.keyName}`);
      lines.push(`  ServerAliveInterval 30`);
      lines.push(`  ServerAliveCountMax 3`);
      lines.push("");
    }
    return lines.join("\n");
  }, [linuxOnly]);

  const copy = async () => {
    await navigator.clipboard.writeText(config);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  };

  const download = () => {
    const blob = new Blob([config], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "vmui-ssh-config";
    a.click();
    URL.revokeObjectURL(url);
  };

  if (linuxOnly.length === 0) {
    return (
      <Card>
        <CardContent className="py-12 text-center text-sm text-muted">
          No reachable Linux VMs yet — once an instance has a public IP, it'll appear here.
        </CardContent>
      </Card>
    );
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2 text-base">
          <FileCode className="h-4 w-4" />
          ~/.ssh/config snippet
          <Badge variant="info" className="ml-2 text-[10px]">
            {linuxOnly.length} hosts
          </Badge>
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-3">
        <pre className="max-h-72 overflow-auto rounded border border-[var(--color-border)] bg-[var(--color-bg)]/60 p-3 font-mono text-[11px]">
          {config}
        </pre>
        <div className="flex items-center gap-2">
          <Button size="sm" onClick={copy}>
            {copied ? <Check className="h-3.5 w-3.5" /> : <Copy className="h-3.5 w-3.5" />}
            {copied ? "Copied" : "Copy"}
          </Button>
          <Button size="sm" variant="ghost" onClick={download}>
            <Download className="h-3.5 w-3.5" /> Download
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}
